[pytest]
addopts = 
    --alluredir=test-reports/allure-results

markers =
    smoke: Smoke tests
    regression: Regression tests
    ui: UI tests
    api: API tests
    critical: Critical business flow